version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: appdb
    ports:
      - "3308:3306"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

  api:
    build: ./backend
    ports:
      - "3003:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: pass123
      DB_NAME: appdb
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3002:3000"
    depends_on:
      - api
